In [1]:
import numpy as np

In [2]:
grid = np.zeros((2,4))
print(grid)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [64]:
states = {}
rewards = []
counter = 0
#Im possesion 0
for possession in [0,1]:
    for row in range(grid.shape[0]):
        for column in range(grid.shape[1]):

            for i in range(2):
                for j in range(4):

                    if (row,column) == (i,j):
                        continue
                    else:
                        state = (possession, (row,column), (i,j))
                        states[state] = counter
                        counter+=1
                        #states.append(state)

                        #check if left side goal and opp has possession - reward should be [-100, 100] - I lose 100 he gains 100 for scoring in my goal
                        #or
                        #check if left side goal and I have possession - reward should be [-100, 100] - I lose 100 he gains 100 for me scoring in my own goal
                        if ((i,j) in [(0,0), (1,0)] and possession == 1) | ((row,column) in [(0,0), (1,0)] and possession == 0):
                            reward = [100, -100]
                            rewards.append(reward)
                        #check if right side goal and opp has possession - reward should be [100, -100] - I gain 100 he loses 100 for scoring in his own goal
                        #or
                        #check if right side goal and I have possession - reward should be [100, -100] - I gain 100 he loses 100 for me scoring in his goal
                        elif ((i,j) in [(0,3), (1,3)] and possession == 1) or ((row,column) in [(0,3), (1,3)] and possession==0):
                            reward = [-100, 100]
                            rewards.append(reward)
                        #no rewards for anything else
                        else:
                            reward = [0 , 0]
                            rewards.append(reward)

                       

         
                        

In [68]:
actions

[((-1, 0), (-1, 0)),
 ((1, 0), (-1, 0)),
 ((0, 1), (-1, 0)),
 ((0, -1), (-1, 0)),
 ((0, 0), (-1, 0)),
 ((-1, 0), (1, 0)),
 ((1, 0), (1, 0)),
 ((0, 1), (1, 0)),
 ((0, -1), (1, 0)),
 ((0, 0), (1, 0)),
 ((-1, 0), (0, 1)),
 ((1, 0), (0, 1)),
 ((0, 1), (0, 1)),
 ((0, -1), (0, 1)),
 ((0, 0), (0, 1)),
 ((-1, 0), (0, -1)),
 ((1, 0), (0, -1)),
 ((0, 1), (0, -1)),
 ((0, -1), (0, -1)),
 ((0, 0), (0, -1)),
 ((-1, 0), (0, 0)),
 ((1, 0), (0, 0)),
 ((0, 1), (0, 0)),
 ((0, -1), (0, 0)),
 ((0, 0), (0, 0))]

In [53]:
list_of_actions = [(-1,0), (1,0), (0,1), (0,-1), (0,0)]

In [67]:
actions = []
for a in list_of_actions:
    for b in list_of_actions:
        action = (b,a)
        actions.append(action)

In [91]:
np.random.choice([0,1], size=1)

array([1])

In [57]:
A = np.array([[-4, -4],
       [ 4, -4],
       [ 1, -4],
       [-1, -4],
       [ 0, -4],
       [-4,  4],
       [ 4,  4],
       [ 1,  4],
       [-1,  4],
       [ 0,  4],
       [-4,  1],
       [ 4,  1],
       [ 1,  1],
       [-1,  1],
       [ 0,  1],
       [-4, -1],
       [ 4, -1],
       [ 1, -1],
       [-1, -1],
       [ 0, -1],
       [-4,  0],
       [ 4,  0],
       [ 1,  0],
       [-1,  0],
       [ 0,  0]])